const productDetailsData = [
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "tops",
        details: "Discover our exquisite collection of women's tops featuring trendy designs, breathable fabrics, and versatile styles perfect for layering or standalone wear. From basic tees to fashionable blouses for every occasion.",
        Heighlights: [
            "Hand cut and sewn locally",
            "Dyed with our proprietary colors",
            "Pre-washed & pre-shrunk",
            "Ultra-soft 100% cotton",
        ],
        Details: "Shop comfortable tops for office, casual outings",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "dress",
        details: "Elegant women's dresses for every occasion - from casual summer dresses to formal evening gowns. Perfect for weddings, parties, office wear, and daily fashion statements with flattering silhouettes.",
        Heighlights: [
            "Premium quality fabrics",
            "Expert tailoring and fit",
            "Easy care and maintenance",
            "Available in multiple sizes",
        ],
        Details: "Complete your wardrobe with diverse dress collection",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "women jeans",
        details: "Comfortable and stylish women's jeans designed for perfect fit and everyday wear. Available in various rises, washes, and styles including skinny, straight, and bootcut for all body types.",
        Heighlights: [
            "Premium denim quality",
            "Comfort stretch fabric",
            "Multiple wash options",
            "Perfect fit guarantee",
        ],
        Details: "Find your perfect pair of jeans for any occasion",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "lengha choli",
        details: "Exquisite traditional lengha choli sets for weddings, festivals, and special occasions. Featuring intricate embroidery, luxurious fabrics, and authentic Indian craftsmanship with beautiful designs.",
        Heighlights: [
            "Handcrafted embroidery",
            "Premium silk and fabrics",
            "Custom sizing available",
            "Traditional designs",
        ],
        Details: "Traditional ethnic wear for grand celebrations",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "sweaters",
        details: "Warm and cozy women's sweaters perfect for winter fashion. From chunky knits to lightweight cardigans, stay stylish and comfortable in cold weather with premium wool blends.",
        Heighlights: [
            "Premium wool blends",
            "Soft and non-itchy",
            "Machine washable",
            "Classic and modern styles",
        ],
        Details: "Stay warm in style with our sweater collection",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "t-shirts",
        details: "Comfortable everyday t-shirts for women in various necklines, sleeve lengths, and fabrics. Perfect for casual wear, workouts, and layering with 100% cotton comfort.",
        Heighlights: [
            "100% cotton fabric",
            "Pre-shrunk material",
            "Multiple color options",
            "Regular and slim fits",
        ],
        Details: "Essential t-shirts for your daily wardrobe needs",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "jackets",
        details: "Stylish women's jackets for all seasons - from denim jackets to formal blazers and winter coats. Combine fashion with functionality for various weather conditions.",
        Heighlights: [
            "Weather appropriate",
            "Durable materials",
            "Multiple style options",
            "Comfortable lining",
        ],
        Details: "Complete your outfits with perfect jacket styles",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "gouns",
        details: "Elegant gouns blending traditional Indian aesthetics with contemporary designs. Perfect for festivals, parties, and cultural events with beautiful drapes and embellishments.",
        Heighlights: [
            "Intricate detailing",
            "Luxurious fabrics",
            "Perfect drape",
            "Rich color palette",
        ],
        Details: "Contemporary ethnic wear for modern women style",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "sarees",
        details: "Traditional Indian sarees in various fabrics including cotton, silk, georgette, and chiffon. From daily wear to bridal collections with authentic traditional weaves.",
        Heighlights: [
            "Authentic designs",
            "Premium fabrics",
            "Easy to drape",
            "Wide color range",
        ],
        Details: "Experience the elegance of traditional saree wear",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "kurtas",
        details: "Comfortable and stylish kurtas for women, perfect for ethnic casual wear. Available in various lengths, fabrics, and designs for everyday elegance and comfort.",
        Heighlights: [
            "Comfortable fit",
            "Easy care fabrics",
            "Traditional motifs",
            "Multiple size options",
        ],
        Details: "Ethnic comfort meets modern style fashion wear",
    },

    // Women - Accessories
    {
        topLevelCategory: "women",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "watches",
        details: "Elegant women's watches combining precision timekeeping with fashion-forward designs. From minimalist styles to statement pieces for every occasion and outfit combination.",
        Heighlights: [
            "Precision movement",
            "Quality materials",
            "Water resistant",
            "Stylish designs",
        ],
        Details: "Timepieces that complement your personal style",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "wallets",
        details: "Practical and stylish women's wallets with multiple compartments for cards, currency, and coins. Designed for organization without compromising on style and fashion.",
        Heighlights: [
            "Genuine leather",
            "Multiple compartments",
            "RFID protection",
            "Compact design",
        ],
        Details: "Organize your essentials in style and security",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "bags",
        details: "Fashionable women's bags including handbags, totes, clutches, and crossbody bags. Combine functionality with trend-setting designs for every occasion and need.",
        Heighlights: [
            "Durable materials",
            "Spacious compartments",
            "Comfortable handles",
            "Trendy designs",
        ],
        Details: "Carry your world in style and convenience",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "sunglasses",
        details: "Stylish women's sunglasses offering 100% UV protection with fashionable frame designs. Protect your eyes while enhancing your fashion statement and style.",
        Heighlights: [
            "UV protection",
            "Scratch-resistant",
            "Lightweight frames",
            "Trendy designs",
        ],
        Details: "Protect your eyes with stylish sunglasses wear",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "hats",
        details: "Fashionable hats for women offering sun protection and style enhancement. From wide-brimmed sun hats to trendy baseball caps for various occasions.",
        Heighlights: [
            "Sun protection",
            "Quality materials",
            "Comfortable fit",
            "Versatile styles",
        ],
        Details: "Complete your look with perfect headwear style",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "belts",
        details: "Stylish women's belts that combine functionality with fashion. Perfect for defining your waist and accessorizing your outfits with various designs.",
        Heighlights: [
            "Genuine leather",
            "Adjustable sizing",
            "Trendy buckles",
            "Durable construction",
        ],
        Details: "Accessorize and define your silhouette perfectly",
    },

    // Women - Brands
    {
        topLevelCategory: "women",
        secondLevelCategory: "brands",
        thirdLevelCategory: "Re-Arranged",
        details: "Re-Arranged offers contemporary women's fashion with unique designs that blend modern aesthetics with comfortable wearability for the fashion-forward woman.",
        Heighlights: [
            "Unique designs",
            "Premium quality",
            "Contemporary styles",
            "Excellent craftsmanship",
        ],
        Details: "Redefining contemporary women's fashion style",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "brands",
        thirdLevelCategory: "counterfiet",
        details: "Counterfeit brand brings edgy, urban-inspired fashion with bold statements and alternative styles for women who dare to be different and unique.",
        Heighlights: [
            "Edgy designs",
            "Urban styles",
            "Bold statements",
            "Quality materials",
        ],
        Details: "For the bold and unconventional fashion lovers",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "brands",
        thirdLevelCategory: "full nelson",
        details: "Full Nelson offers classic American style with modern updates, focusing on comfortable, wearable fashion that stands the test of time and trends.",
        Heighlights: [
            "Classic American style",
            "Modern twists",
            "Comfortable fits",
            "Durable construction",
        ],
        Details: "Classic style meets modern comfort and fashion",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "brands",
        thirdLevelCategory: "sun glasses",
        details: "Premium branded sunglasses offering complete eye protection with fashionable frame designs and advanced lens technology for women's style.",
        Heighlights: [
            "Premium lenses",
            "Fashionable frames",
            "UV protection",
            "Durable materials",
        ],
        Details: "Branded sunglasses for style and eye protection",
    },
    {
        topLevelCategory: "women",
        secondLevelCategory: "brands",
        thirdLevelCategory: "my way",
        details: "My Way empowers women to express their individuality through customizable fashion options and personalized style statements and creations.",
        Heighlights: [
            "Customizable options",
            "Personalized designs",
            "Quality craftsmanship",
            "Individual expression",
        ],
        Details: "Your style, your way with personalized fashion",
    },

    // Men - Clothing
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "mens kurtas",
        details: "Traditional and contemporary men's kurtas perfect for ethnic occasions, festivals, and casual wear. Available in various fabrics and elegant designs.",
        Heighlights: [
            "Comfortable fabrics",
            "Perfect fit",
            "Traditional embroidery",
            "Easy maintenance",
        ],
        Details: "Ethnic elegance for modern men's fashion wear",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "shirt",
        details: "Classic and modern men's shirts for formal, casual, and party wear. Featuring various fits, collars, and fabric options for every occasion and style.",
        Heighlights: [
            "Premium cotton",
            "Wrinkle-resistant",
            "Multiple fits",
            "Long-lasting colors",
        ],
        Details: "Perfect shirts for every occasion and meeting",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "men jeans",
        details: "Durable and stylish men's jeans in various fits including slim, regular, and relaxed. Designed for comfort and long-lasting wear and durability.",
        Heighlights: [
            "Premium denim",
            "Comfort stretch",
            "Multiple washes",
            "Perfect fit",
        ],
        Details: "Classic denim for everyday wear and comfort",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "sweaters",
        details: "Warm and comfortable men's sweaters for winter fashion. From V-necks to turtlenecks, stay warm in style with premium wool blends and designs.",
        Heighlights: [
            "Premium wool blends",
            "Comfortable wear",
            "Classic designs",
            "Easy maintenance",
        ],
        Details: "Winter essentials for men's fashion and warmth",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "T-Shirts",
        details: "Comfortable men's t-shirts in various necklines, sleeve lengths, and fabrics. Perfect for casual wear, sports, and layering with comfort.",
        Heighlights: [
            "100% cotton",
            "Pre-shrunk",
            "Multiple colors",
            "Comfortable fit",
        ],
        Details: "Essential t-shirts for men's daily wardrobe use",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "jackets",
        details: "Stylish men's jackets including denim, bomber, leather, and formal blazers. Combine functionality with fashion for all seasons and occasions.",
        Heighlights: [
            "Weather protection",
            "Durable construction",
            "Multiple styles",
            "Comfortable fit",
        ],
        Details: "Complete your look with perfect jacket styles",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "clothing",
        thirdLevelCategory: "activewears",
        details: "Performance-oriented activewear for men designed for workouts, sports, and athletic activities. Featuring advanced moisture-wicking technology.",
        Heighlights: [
            "Moisture-wicking",
            "Flexible fabric",
            "Quick dry",
            "Comfortable fit",
        ],
        Details: "Performance wear for active men and athletes",
    },

    // Men - Accessories
    {
        topLevelCategory: "men",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "watches",
        details: "Sophisticated men's watches combining precision engineering with masculine design. From sporty chronographs to elegant dress watches for men.",
        Heighlights: [
            "Precision movement",
            "Durable materials",
            "Water resistant",
            "Classic designs",
        ],
        Details: "Timekeeping with masculine style and precision",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "wallets",
        details: "Practical men's wallets designed for organization and durability. Featuring multiple card slots, currency compartments, and slim profiles.",
        Heighlights: [
            "Genuine leather",
            "Multiple compartments",
            "RFID protection",
            "Slim design",
        ],
        Details: "Organize your essentials efficiently and securely",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "bags",
        details: "Functional men's bags including backpacks, messenger bags, and laptop bags. Designed for work, travel, and everyday carry with style.",
        Heighlights: [
            "Durable materials",
            "Spacious design",
            "Comfortable carry",
            "Practical features",
        ],
        Details: "Carry your gear in style and convenience",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "sunglasses",
        details: "Stylish men's sunglasses offering complete UV protection with masculine frame designs. Protect your eyes with style and sophistication.",
        Heighlights: [
            "UV protection",
            "Scratch-resistant",
            "Durable frames",
            "Masculine designs",
        ],
        Details: "Eye protection with masculine appeal and style",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "hats",
        details: "Fashionable men's hats for sun protection and style. Including baseball caps, fedoras, and beanies for different seasons and occasions.",
        Heighlights: [
            "Sun protection",
            "Quality materials",
            "Comfortable fit",
            "Casual styles",
        ],
        Details: "Headwear for every occasion and season needs",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "accessories",
        thirdLevelCategory: "belts",
        details: "Classic men's belts combining functionality with style. Available in various leathers and buckle designs for formal and casual wear.",
        Heighlights: [
            "Genuine leather",
            "Adjustable sizing",
            "Classic buckles",
            "Durable construction",
        ],
        Details: "Essential accessory for every man's wardrobe",
    },

    // Men - Brands
    {
        topLevelCategory: "men",
        secondLevelCategory: "brnad",
        thirdLevelCategory: "Re-Arranged",
        details: "Re-Arranged offers contemporary menswear with unique designs and premium quality materials for the modern man who values style and comfort.",
        Heighlights: [
            "Unique designs",
            "Premium quality",
            "Contemporary styles",
            "Excellent craftsmanship",
        ],
        Details: "Redefining contemporary men's fashion style",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "brnad",
        thirdLevelCategory: "counterfiet",
        details: "Counterfeit brand brings edgy menswear with bold statements and urban style influences for men who want to stand out from the crowd.",
        Heighlights: [
            "Edgy designs",
            "Urban styles",
            "Bold statements",
            "Quality materials",
        ],
        Details: "For men who dare to be different in fashion",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "brnad",
        thirdLevelCategory: "full nelson",
        details: "Full Nelson brand offers classic menswear with modern updates and comfortable fits that combine traditional style with contemporary fashion.",
        Heighlights: [
            "Classic style",
            "Modern updates",
            "Comfortable fits",
            "Durable construction",
        ],
        Details: "Classic menswear with modern comfort features",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "brnad",
        thirdLevelCategory: "sun glasses",
        details: "Premium branded sunglasses for men offering advanced eye protection with stylish frame designs and superior lens technology for men.",
        Heighlights: [
            "Premium lenses",
            "Stylish frames",
            "UV protection",
            "Durable materials",
        ],
        Details: "Branded sunglasses for men's style and protection",
    },
    {
        topLevelCategory: "men",
        secondLevelCategory: "brnad",
        thirdLevelCategory: "my way",
        details: "My Way brand empowers individual expression through customizable mens fashion items that allow personal style statements and creativity.",
        Heighlights: [
            "Customizable options",
            "Personalized designs",
            "Quality craftsmanship",
            "Individual expression",
        ],
        Details: "Your style, your way with personalized fashion",
    }
];


export default productDetailsData;